# These are supported funding model platforms


patreon: HK_PhAntoM
https://patreon.com/user?u=59184091&utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=creatorshare_creator&utm_content=join_link
